// flow-typed signature: 7e04e0c710b243bd9489c977b7b18841
// flow-typed version: <<STUB>>/clean-webpack-plugin_v0.1.17/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clean-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clean-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'clean-webpack-plugin/index' {
  declare module.exports: $Exports<'clean-webpack-plugin'>;
}
declare module 'clean-webpack-plugin/index.js' {
  declare module.exports: $Exports<'clean-webpack-plugin'>;
}
